/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;
import java.sql.*;
import java.util.Vector;

/**
 *
 * @author Ramchandra Patil
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        PatientPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        opd_sho_jTextField = new javax.swing.JTextField();
        op_name_jTextField = new javax.swing.JTextField();
        opd_address_jTextField = new javax.swing.JTextField();
        opd_contact_jTextField = new javax.swing.JTextField();
        opd_reason_regis_jTextField = new javax.swing.JTextField();
        opd_doc_id_jTextField = new javax.swing.JTextField();
        opd_date_jTextField = new javax.swing.JTextField();
        opd_age_jTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        OPDTable = new javax.swing.JTable();
        opd_submit_jButton = new javax.swing.JButton();
        opd_del_jButton = new javax.swing.JButton();
        opd_update_jButton = new javax.swing.JButton();
        DoctorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorTable = new javax.swing.JTable();
        DoctorEntryLabel = new javax.swing.JLabel();
        doctor_id = new javax.swing.JLabel();
        doc_id_jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doc_NAME_jTextField = new javax.swing.JTextField();
        Assistant_name_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        doc_spec_jTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        doc_time_jTextField = new javax.swing.JComboBox<>();
        doc_submit_jButton = new javax.swing.JButton();
        doc_del_jButton = new javax.swing.JButton();
        doc_contact_jTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        doc_update_jButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        OPDPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pat_namejTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        pat_nojTextField = new javax.swing.JTextField();
        pat_dobjTextField = new javax.swing.JTextField();
        pat_blood_groupjTextField = new javax.swing.JTextField();
        pat_contactjTextField = new javax.swing.JTextField();
        pat_emerg_personjTextField = new javax.swing.JTextField();
        pat_emerg_contjTextField = new javax.swing.JTextField();
        pat_med_treatmentjTextField = new javax.swing.JTextField();
        pat_doc_idjTextField = new javax.swing.JTextField();
        pat_adm_date_jTextField = new javax.swing.JTextField();
        pat_gender_jComboBox = new javax.swing.JComboBox<>();
        pat_discharge_date_jTextField = new javax.swing.JTextField();
        pat_submit_jButton = new javax.swing.JButton();
        pat_update_jButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PatientTable = new javax.swing.JTable();
        pat_del_jButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("OPD Entry");

        opd_sho_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd_sho_jTextFieldActionPerformed(evt);
            }
        });

        op_name_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_name_jTextFieldActionPerformed(evt);
            }
        });

        opd_contact_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd_contact_jTextFieldActionPerformed(evt);
            }
        });

        opd_doc_id_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opd_doc_id_jTextFieldActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("SHO:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Name:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Address:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Contact No:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("Reason for registration:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Doctor Id:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Date:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Age:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Gender:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        Vector<Object[]> data = new Vector<>();
        // https://stackoverflow.com/a/27276523
        String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        username = "root",
        password = "";
        Dbconnect connect = new Dbconnect(dbname, username, password);
        try {
            ResultSet res = connect.getData("select * from OPD");

            Object[] row; // stores row data
            System.out.println("Records from database: ");
            while (res.next()){
                // checks all the entries from the DB (will not enter while loop if no entries)
                String SHO = res.getString("SHO");
                String Name = res.getString("Name");
                String Address = res.getString("Address");
                int Contact_no= res.getInt("Contact_no");
                String Reason_for_registration= res.getString("Reason_for_registration");
                int Doctor_id = res.getInt("Doctor_id");
                Date Date= res.getDate("Date");
                int Age= res.getInt("Age");
                String Gender= res.getString("Gender");
                System.out.printf("SHO : %s\nName: %s\nAddress :%s\nContact_no : %s\nReason_for_registration : %s\nDoctor_id : %s\nDate : %s\nAge : %s\nGender : %s\n",SHO,Name,Address,Contact_no,Reason_for_registration,Doctor_id,Date,Age,Gender );

                row = new Object[] {SHO,Name,Address,Contact_no,Reason_for_registration,Doctor_id,Date,Age,Gender };

                data.add(row);
            }
        } catch (SQLException ex) {
            System.out.println("Fetching error: ");
            ex.printStackTrace();
        }
        OPDTable.setModel(new javax.swing.table.DefaultTableModel(
            data.toArray(  new Object [][]{}),
            new String [] {
                "SHO", "Name", "Address", "Contact No", "Reason for registration", "Doctor Id", "Date", "Age", "Gender"
            }
        ));
        jScrollPane3.setViewportView(OPDTable);

        opd_submit_jButton.setText("SUBMIT");
        opd_submit_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opd_to_database(evt);
            }
        });

        opd_del_jButton.setText("DELETE");

        opd_update_jButton.setText("UPDATE");

        javax.swing.GroupLayout PatientPanelLayout = new javax.swing.GroupLayout(PatientPanel);
        PatientPanel.setLayout(PatientPanelLayout);
        PatientPanelLayout.setHorizontalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opd_sho_jTextField)
                            .addComponent(op_name_jTextField)
                            .addComponent(opd_address_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(opd_contact_jTextField)))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opd_reason_regis_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(opd_doc_id_jTextField)
                            .addComponent(opd_date_jTextField)
                            .addComponent(opd_age_jTextField)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PatientPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opd_submit_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opd_update_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opd_del_jButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PatientPanelLayout.setVerticalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(opd_sho_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(op_name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(opd_address_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(opd_contact_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opd_reason_regis_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opd_doc_id_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(16, 16, 16)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(opd_date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opd_age_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(40, 40, 40)
                .addGroup(PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opd_submit_jButton)
                    .addComponent(opd_del_jButton)
                    .addComponent(opd_update_jButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );

        jTabbedPane.addTab("OPD", PatientPanel);

        Vector<Object[]> data = new Vector<>();
        // https://stackoverflow.com/a/27276523
        String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        username = "root",
        password = "";
        Dbconnect connect = new Dbconnect(dbname, username, password);
        try {
            ResultSet res = connect.getData("select * from doctors");
            Object[] row; // stores row data
            System.out.println("Records from database: ");
            while (res.next()){
                // checks all the entries from the DB (will not enter while loop if no entries)
                int Doctor_id= res.getInt("Doctor_id");
                String Name = res.getString("Name");
                String Assistant_name = res.getString("Assistant_name");
                String Specialisation= res.getString("Specialisation");
                int Contact_no= res.getInt("Contact_no");
                Date Visiting_hours= res.getDate("Visiting_hours");
                System.out.printf("Doctor_id : %s\nName: %s\nAssistant_name : %s\nSpecialisation : %s\nContact_no : %s\nVisiting_hours : %s\n",Doctor_id,Name,Assistant_name,Specialisation,Contact_no,Visiting_hours );
                row = new Object[] {Doctor_id, Name, Assistant_name, Specialisation, Contact_no, Visiting_hours};
                data.add(row);
            }
        } catch (SQLException ex) {
            System.out.println("Fetching error: ");
            ex.printStackTrace();
        }
        DoctorTable.setModel(new javax.swing.table.DefaultTableModel(
            data.toArray(new Object[][]{}),
            new String [] {
                "Doctor id", "Name", "Assistant Name", "Specialisation", "Contact no", "Visiting Hours"
            }
        ));
        jScrollPane1.setViewportView(DoctorTable);

        DoctorEntryLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DoctorEntryLabel.setText("Doctor Entry");

        doctor_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doctor_id.setText("Doctor ID:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, doc_id_jTextField, org.jdesktop.beansbinding.ObjectProperty.create(), doctor_id, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        doc_id_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_id_jTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, doc_NAME_jTextField, org.jdesktop.beansbinding.ObjectProperty.create(), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Assistant Name:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Assistant_name_jTextField, org.jdesktop.beansbinding.ObjectProperty.create(), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Specialisation:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, doc_spec_jTextField, org.jdesktop.beansbinding.ObjectProperty.create(), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        doc_spec_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_spec_jTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Visiting Hours:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, doc_time_jTextField, org.jdesktop.beansbinding.ObjectProperty.create(), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        doc_time_jTextField.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] {
                "09:00-13:00",
                "15:30-19:30",
                "20:00-21:30"
            }));
            doc_time_jTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    doc_time_jTextFieldActionPerformed(evt);
                }
            });

            doc_submit_jButton.setText("SUBMIT");
            doc_submit_jButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    doc_submit_jButtonActionPerformed(evt);
                }
            });

            doc_del_jButton.setText("DELETE");
            doc_del_jButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    doc_del_jButtonActionPerformed(evt);
                }
            });

            jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel28.setText("Contact No:");

            doc_update_jButton.setText("UPDATE");

            jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            jLabel29.setText("Doctor Entry");

            javax.swing.GroupLayout DoctorPanelLayout = new javax.swing.GroupLayout(DoctorPanel);
            DoctorPanel.setLayout(DoctorPanelLayout);
            DoctorPanelLayout.setHorizontalGroup(
                DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DoctorPanelLayout.createSequentialGroup()
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DoctorPanelLayout.createSequentialGroup()
                            .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DoctorPanelLayout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel1))
                                .addGroup(DoctorPanelLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(doctor_id))
                                .addGroup(DoctorPanelLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel4))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Assistant_name_jTextField)
                                .addComponent(doc_NAME_jTextField)
                                .addComponent(doc_id_jTextField)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorPanelLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(doc_spec_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(doc_contact_jTextField)
                                            .addComponent(doc_time_jTextField, 0, 120, Short.MAX_VALUE)))))
                            .addGap(39, 39, 39))
                        .addGroup(DoctorPanelLayout.createSequentialGroup()
                            .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DoctorPanelLayout.createSequentialGroup()
                                    .addComponent(doc_submit_jButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(doc_update_jButton)
                                    .addGap(14, 14, 14)
                                    .addComponent(doc_del_jButton))
                                .addGroup(DoctorPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel29)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(426, 426, 426)
                    .addComponent(DoctorEntryLabel))
            );
            DoctorPanelLayout.setVerticalGroup(
                DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DoctorPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DoctorEntryLabel)
                        .addComponent(jLabel29))
                    .addGap(18, 18, 18)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doctor_id)
                        .addComponent(doc_id_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(doc_NAME_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Assistant_name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(doc_spec_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doc_contact_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addGap(18, 18, 18)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(doc_time_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doc_submit_jButton)
                        .addComponent(doc_update_jButton)
                        .addComponent(doc_del_jButton))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            );

            jTabbedPane.addTab("Doctor", DoctorPanel);

            OPDPanel.setPreferredSize(new java.awt.Dimension(100, 100));

            jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
            jLabel5.setText("Patient Entry");

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel6.setText("Patient no:");

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel7.setText("Name:");

            jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel8.setText("DOB:");

            jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel9.setText("Blood Group:");

            jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel10.setText("Gender:");

            jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel11.setText("Contact No:");

            jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
            jLabel12.setText("Emergency Person:");

            jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
            jLabel13.setText("Emergency Contact no:");

            jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel15.setText("Date of admission:");

            jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
            jLabel14.setText("Medical Treatement:");

            jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel16.setText("Date of discharge:");

            jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jLabel17.setText("Doctor Id:");

            pat_contactjTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pat_contactjTextFieldActionPerformed(evt);
                }
            });

            pat_emerg_contjTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pat_emerg_contjTextFieldActionPerformed(evt);
                }
            });

            pat_adm_date_jTextField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pat_adm_date_jTextFieldActionPerformed(evt);
                }
            });

            pat_gender_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Rather not say" }));

            pat_submit_jButton.setText("SUBMIT");
            pat_submit_jButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pat_submit_jButtonActionPerformed(evt);
                }
            });

            pat_update_jButton.setText("UPDATE");

            Vector<Object[]> data = new Vector<>();
            // https://stackoverflow.com/a/27276523
            String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            username = "root",
            password = "";
            Dbconnect connect = new Dbconnect(dbname, username, password);
            try {
                ResultSet res = connect.getData("select * from patient");

                Object[] row; // stores row data
                System.out.println("Records from database: ");
                while (res.next()){
                    // checks all the entries from the DB (will not enter while loop if no entries)
                    int patient_id= res.getInt("patient_no");
                    String Name = res.getString("Name");
                    Date DOB= res.getDate("DOB");
                    String Blood_group= res.getString("Blood_group");
                    String Gender= res.getString("Gender");
                    int Contact_no= res.getInt("Contact_no");
                    String Emergency_person= res.getString("Emergency_person");
                    int Emergency_contact_no= res.getInt("Emergency_contact_no");
                    String Medical_treatment= res.getString("Medical_treatment");
                    Date Date_of_admission= res.getDate("Date_of_admission");
                    Date Date_of_discharge= res.getDate("Date_of_discharge");
                    int Doctor_id = res.getInt("Doctor_id");
                    System.out.printf("pateint_no : %s\nName: %s\nDOB : %s\nBlood_group : %s\nGender : %s\nContact_no : %s\nEmergency_person : %s\nEmergency_contact_no : %s\nMedical_treatment : %s\nDate_of_admission : %s\nDate_of_discharge : %s\nDoctor_id : %s\n",pateint_no,Name,DOB, Blood_group,Gender,Contact_no,Emergency_person,Emergency_contact_no,Medical_treatment,Date_of_admission,Date_of_discharge,Doctor_id );

                    row = new Object[] {patient_no,Name,DOB,Blood_group,Gender,Contact_no,Emergency_person,Emergency_contact_no,Medical_treatment,Date_of_admission,Date_of_discharge,Doctor_id };

                    data.add(row);
                }
            } catch (SQLException ex) {
                System.out.println("Fetching error: ");
                ex.printStackTrace();
            }
            PatientTable.setModel(new javax.swing.table.DefaultTableModel(
                data.toArray( new Object [][] {}),
                new String [] {
                    "Patient no", "Name", "DOB", "Blood Group", "Gender", "Contact no", "Emergency Person", "Emergency Contact no", "Medical Treatment", "Date of Admission", "Date of Discharge", "Doctor Id"
                }
            ));
            jScrollPane2.setViewportView(PatientTable);

            pat_del_jButton.setText("DELETE");

            javax.swing.GroupLayout OPDPanelLayout = new javax.swing.GroupLayout(OPDPanel);
            OPDPanel.setLayout(OPDPanelLayout);
            OPDPanelLayout.setHorizontalGroup(
                OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OPDPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OPDPanelLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(OPDPanelLayout.createSequentialGroup()
                                    .addComponent(pat_submit_jButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(pat_update_jButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(pat_del_jButton))
                                .addGroup(OPDPanelLayout.createSequentialGroup()
                                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addGroup(OPDPanelLayout.createSequentialGroup()
                                            .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9))
                                            .addGap(1, 1, 1))
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel12)
                                        .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pat_nojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_dobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_blood_groupjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_gender_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_contactjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_emerg_personjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_emerg_contjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_med_treatmentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_doc_idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_adm_date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pat_discharge_date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5))
                    .addGap(43, 43, 43))
            );
            OPDPanelLayout.setVerticalGroup(
                OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPDPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(pat_nojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(pat_namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(pat_dobjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(pat_blood_groupjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(pat_gender_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(pat_contactjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(pat_emerg_personjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pat_emerg_contjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(pat_med_treatmentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pat_doc_idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pat_adm_date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pat_discharge_date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(OPDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pat_submit_jButton)
                        .addComponent(pat_update_jButton)
                        .addComponent(pat_del_jButton))
                    .addContainerGap())
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            );

            jTabbedPane.addTab("Patient", OPDPanel);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            bindingGroup.bind();

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void opd_sho_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd_sho_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opd_sho_jTextFieldActionPerformed

    private void op_name_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_name_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_name_jTextFieldActionPerformed

    private void opd_contact_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd_contact_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opd_contact_jTextFieldActionPerformed

    private void opd_doc_id_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opd_doc_id_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opd_doc_id_jTextFieldActionPerformed

    private void pat_adm_date_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_adm_date_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_adm_date_jTextFieldActionPerformed

    private void pat_contactjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_contactjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_contactjTextFieldActionPerformed

    private void pat_emerg_contjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_emerg_contjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pat_emerg_contjTextFieldActionPerformed

    private void doc_del_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_del_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_del_jButtonActionPerformed

    private void doc_submit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_submit_jButtonActionPerformed
        // https://stackoverflow.com/a/27276523
        String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        username = "root",
        password = "";
        Dbconnect connect = new Dbconnect(dbname, username, password);
        try {
            Connection conn = connect.getConnection();  // step 1: get connected to database
            
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO opd VALUES (?,?,?,?,?,?)");   // step 2: prepare a statement to push to DB
            
            stmt.setInt(1,doc_id_jTextField.getText());   // step 3: fetch data from the form and fill the prepared statement
            stmt.setString(2,doc_NAME_jTextField.getText());
            stmt.setString(3,Assistant_name_jTextField.getText());
            stmt.setString(4,doc_spec_jTextField.getText());
            stmt.setInt(5, Integer.parseInt(doc_contact_jTextField.getText()));
            stmt.setString(6,doc_time_jTextField.getName());
            System.out.println(stmt.executeUpdate() + "records inserted."); // execute the statement. This will cause the data to be pushed.
            conn.close();
        } catch (SQLException ex) {
            System.out.println("Insertion error: ");
            ex.printStackTrace();
        }        
    }                                

    }//GEN-LAST:event_doc_submit_jButtonActionPerformed

    private void doc_time_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_time_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_time_jTextFieldActionPerformed

    private void doc_spec_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_spec_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_spec_jTextFieldActionPerformed

    private void doc_id_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_id_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_id_jTextFieldActionPerformed

    private void opd_to_database(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opd_to_database
        // https://stackoverflow.com/a/27276523
        String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        username = "root",
        password = "";
        Dbconnect connect = new Dbconnect(dbname, username, password);
        try {
            Connection conn = connect.getConnection();  // step 1: get connected to database
            
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO opd VALUES (?,?,?,?,?,?,?,?,?)");   // step 2: prepare a statement to push to DB
            
            stmt.setString(1,opd_sho_jTextField.getText());   // step 3: fetch data from the form and fill the prepared statement
            stmt.setString(2,op_name_jTextField.getText());
            stmt.setString(3,opd_address_jTextField.getText());
            stmt.setInt(4,Integer.parseInt(opd_contact_jTextField.getText()));
            stmt.setString(5,opd_reason_regis_jTextField.getText());
            stmt.setInt(6, Integer.parseInt(opd_doc_id_jTextField.getText()));
            stmt.setDate(7,new Date(Date.parse(opd_date_jTextField.getText())));
            stmt.setInt(8,Integer.parseInt(opd_age_jTextField.getText()));
            stmt.setString(9,jComboBox2.getName());
            System.out.println(stmt.executeUpdate() + "records inserted."); // execute the statement. This will cause the data to be pushed.
            conn.close();
        } catch (SQLException ex) {
            System.out.println("Insertion error: ");
            ex.printStackTrace();
        }        
    }//GEN-LAST:event_opd_to_database

    private void pat_submit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pat_submit_jButtonActionPerformed
               // https://stackoverflow.com/a/27276523
        String dbname = "jdbc:mysql://localhost:3306/hospital_management_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        username = "root",
        password = "";
        Dbconnect connect = new Dbconnect(dbname, username, password);
        try {
            Connection conn = connect.getConnection();  // step 1: get connected to database
            
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO opd VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");   // step 2: prepare a statement to push to DB
            
            stmt.setInt(1,pat_nojTextField.getText());   // step 3: fetch data from the form and fill the prepared statement
            stmt.setString(2,pat_namejTextField.getText());
            stmt.setInt(3, Integer.parseInt(pat_dobjTextField.getText()));
            stmt.setString(4,pat_blood_groupjTextField.getText());
            stmt.setString(5,pat_gender_jComboBox.getName());
            stmt.setInt(6,pat_contactjTextField.getText());  
            stmt.setString(7,pat_emerg_personjTextField.getText());
            stmt.setInt(8,pat_emerg_contjTextField.getText());  
            stmt.setString(9,pat_med_treatmentjTextField.getText());
            stmt.setInt(10,pat_doc_idjTextField.getText());  
            stmt.setDate(11,new Date(Date.parse(pat_adm_date_jTextField.getText())));
            stmt.setDate(12,new Date(Date.parse(pat_discharge_date_jTextField.getText())));
            System.out.println(stmt.executeUpdate() + "records inserted."); // execute the statement. This will cause the data to be pushed.
            conn.close();
        } catch (SQLException ex) {
            System.out.println("Insertion error: ");
            ex.printStackTrace();
        }        
    }                                

    }                                                  

    }//GEN-LAST:event_pat_submit_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Assistant_name_jTextField;
    private javax.swing.JLabel DoctorEntryLabel;
    private javax.swing.JPanel DoctorPanel;
    private javax.swing.JTable DoctorTable;
    private javax.swing.JPanel OPDPanel;
    private javax.swing.JTable OPDTable;
    private javax.swing.JPanel PatientPanel;
    private javax.swing.JTable PatientTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField doc_NAME_jTextField;
    private javax.swing.JTextField doc_contact_jTextField;
    private javax.swing.JButton doc_del_jButton;
    private javax.swing.JTextField doc_id_jTextField;
    private javax.swing.JTextField doc_spec_jTextField;
    private javax.swing.JButton doc_submit_jButton;
    private javax.swing.JComboBox<String> doc_time_jTextField;
    private javax.swing.JButton doc_update_jButton;
    private javax.swing.JLabel doctor_id;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField op_name_jTextField;
    private javax.swing.JTextField opd_address_jTextField;
    private javax.swing.JTextField opd_age_jTextField;
    private javax.swing.JTextField opd_contact_jTextField;
    private javax.swing.JTextField opd_date_jTextField;
    private javax.swing.JButton opd_del_jButton;
    private javax.swing.JTextField opd_doc_id_jTextField;
    private javax.swing.JTextField opd_reason_regis_jTextField;
    private javax.swing.JTextField opd_sho_jTextField;
    private javax.swing.JButton opd_submit_jButton;
    private javax.swing.JButton opd_update_jButton;
    private javax.swing.JTextField pat_adm_date_jTextField;
    private javax.swing.JTextField pat_blood_groupjTextField;
    private javax.swing.JTextField pat_contactjTextField;
    private javax.swing.JButton pat_del_jButton;
    private javax.swing.JTextField pat_discharge_date_jTextField;
    private javax.swing.JTextField pat_dobjTextField;
    private javax.swing.JTextField pat_doc_idjTextField;
    private javax.swing.JTextField pat_emerg_contjTextField;
    private javax.swing.JTextField pat_emerg_personjTextField;
    private javax.swing.JComboBox<String> pat_gender_jComboBox;
    private javax.swing.JTextField pat_med_treatmentjTextField;
    private javax.swing.JTextField pat_namejTextField;
    private javax.swing.JTextField pat_nojTextField;
    private javax.swing.JButton pat_submit_jButton;
    private javax.swing.JButton pat_update_jButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
